name: trading_diary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.0
  country_currency_pickers: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "android_icon"
  ios: true
  image_path: "assets/icon/icon_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
